// src/components/ScreenComponent.vue
<template>
  <div
      class="screen"
      :style="{ left: `${position.x}px`, top: `${position.y}px`, width: `${size.width}px`, height: `${size.height}px` }"
  >
    <div class="header" :style="{ backgroundColor: headerColor }" @mousedown="startDrag">{{ headerText }}</div>
    <div class="content">
      <p>{{ content }}</p>
    </div>

    <!-- Resize Handle -->
    <div class="resize-handle" @mousedown="startResize"></div>

    <!-- Reset Button -->
    <button @click="resetPosition" class="reset-btn">Reset</button>
  </div>
</template>

<script>
export default {
  props: {
    headerText: {
      type: String,
      default: 'Screen Header', // Default value for header text
    },
    initialPosition: {
      type: Object,
      default: () => ({ x: 100, y: 100 }), // Default initial position
    },
    initialSize: {
      type: Object,
      default: () => ({ width: 300, height: 200 }), // Default initial size
    },
    content: {
      type: String,
      default: 'This is the content of the screen.', // Default content text
    },
    headerColor: {
      type: String,
      default: '#4CAF50', // Default header color
    },
  },
  data() {
    return {
      position: { ...this.initialPosition }, // Position set from prop
      size: { ...this.initialSize }, // Size set from prop
      dragging: false,
      resizing: false,
      offsetX: 0,
      offsetY: 0,
      resizeOffsetX: 0,
      resizeOffsetY: 0,
      minWidth: 200, // Minimum width of the screen component
      minHeight: 150, // Minimum height of the screen component
      maxWidth: window.innerWidth, // Maximum width constraint
      maxHeight: window.innerHeight, // Maximum height constraint
    };
  },
  methods: {
    // Start dragging the component (moving it)
    startDrag(event) {
      if (event.target.classList.contains('header')) {
        this.dragging = true;
        this.offsetX = event.clientX - this.position.x;
        this.offsetY = event.clientY - this.position.y;
        document.addEventListener('mousemove', this.onMouseMove);
        document.addEventListener('mouseup', this.stopDrag);
      }
    },

    // Start resizing the component (resize the width and height)
    startResize(event) {
      event.preventDefault(); // Prevent text selection while resizing
      this.resizing = true;
      this.resizeOffsetX = event.clientX - this.size.width;
      this.resizeOffsetY = event.clientY - this.size.height;
      document.addEventListener('mousemove', this.onResize);
      document.addEventListener('mouseup', this.stopResize);
    },

    // Move the component when dragging
    onMouseMove(event) {
      if (this.dragging) {
        let newX = event.clientX - this.offsetX;
        let newY = event.clientY - this.offsetY;

        // Prevent dragging out of bounds (constraints)
        newX = Math.max(0, Math.min(newX, this.maxWidth - this.size.width));
        newY = Math.max(0, Math.min(newY, this.maxHeight - this.size.height));

        this.position.x = newX;
        this.position.y = newY;
      }
    },

    // Resize the component when dragging the resize handle
    onResize(event) {
      if (this.resizing) {
        let newWidth = event.clientX - this.resizeOffsetX;
        let newHeight = event.clientY - this.resizeOffsetY;

        // Ensure the width and height are not less than the minimum size
        newWidth = Math.max(this.minWidth, newWidth);
        newHeight = Math.max(this.minHeight, newHeight);

        // Prevent resizing beyond maximum size
        newWidth = Math.min(newWidth, this.maxWidth - this.position.x);
        newHeight = Math.min(newHeight, this.maxHeight - this.position.y);

        this.size.width = newWidth;
        this.size.height = newHeight;
      }
    },

    // Stop dragging the component
    stopDrag() {
      this.dragging = false;
      document.removeEventListener('mousemove', this.onMouseMove);
      document.removeEventListener('mouseup', this.stopDrag);
    },

    // Stop resizing the component
    stopResize() {
      this.resizing = false;
      document.removeEventListener('mousemove', this.onResize);
      document.removeEventListener('mouseup', this.stopResize);
    },

    // Reset position and size to initial values
    resetPosition() {
      this.position = { ...this.initialPosition };
      this.size = { ...this.initialSize };
    },
  },
};
</script>

<style scoped>
.screen {
  position: absolute;
  background-color: #ffffff;
  border: 2px solid #ccc;
  border-radius: 8px;
  box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
}

.header {
  color: white;
  padding: 10px;
  cursor: move;
  text-align: center;
}

.content {
  padding: 10px;
  overflow: auto;
}

.resize-handle {
  position: absolute;
  bottom: 0;
  right: 0;
  width: 16px;
  height: 16px;
  background-color: #2196F3;
  cursor: se-resize; /* Diagonal resize cursor */
}

.reset-btn {
  position: absolute;
  top: 10px;
  right: 10px;
  padding: 5px 10px;
  background-color: #FF5722;
  color: white;
  border: none;
  border-radius: 5px;
  cursor: pointer;
  font-size: 12px;
}
</style>

// src/components/ScreenComponent.tsx
import React, { useState, useEffect, useRef } from 'react';

interface ScreenComponentProps {
    headerText?: string;
    initialPosition?: { x: number; y: number };
    initialSize?: { width: number; height: number };
    content?: string;
    headerColor?: string;
}

const ScreenComponent: React.FC<ScreenComponentProps> = ({
                                                             headerText = 'Screen Header',
                                                             initialPosition = { x: 100, y: 100 },
                                                             initialSize = { width: 300, height: 200 },
                                                             content = 'This is the content of the screen.',
                                                             headerColor = '#4CAF50',
                                                         }) => {
    // State variables for position, size, dragging and resizing
    const [position, setPosition] = useState(initialPosition);
    const [size, setSize] = useState(initialSize);
    const [dragging, setDragging] = useState(false);
    const [resizing, setResizing] = useState(false);
    const [offsetX, setOffsetX] = useState(0);
    const [offsetY, setOffsetY] = useState(0);
    const [resizeOffsetX, setResizeOffsetX] = useState(0);
    const [resizeOffsetY, setResizeOffsetY] = useState(0);

    const minWidth = 200;
    const minHeight = 150;
    const maxWidth = window.innerWidth;
    const maxHeight = window.innerHeight;

    // Refs for the element
    const screenRef = useRef<HTMLDivElement>(null);

    const startDrag = (event: React.MouseEvent) => {
        if (event.target instanceof HTMLElement && event.target.classList.contains('header')) {
            setDragging(true);
            setOffsetX(event.clientX - position.x);
            setOffsetY(event.clientY - position.y);
        }
    };

    const startResize = (event: React.MouseEvent) => {
        event.preventDefault(); // Prevent text selection while resizing
        setResizing(true);
        setResizeOffsetX(event.clientX - size.width);
        setResizeOffsetY(event.clientY - size.height);
    };

    const onMouseMove = (event: MouseEvent) => {
        if (dragging) {
            let newX = event.clientX - offsetX;
            let newY = event.clientY - offsetY;

            // Prevent dragging out of bounds (constraints)
            newX = Math.max(0, Math.min(newX, maxWidth - size.width));
            newY = Math.max(0, Math.min(newY, maxHeight - size.height));

            setPosition({ x: newX, y: newY });
        }

        if (resizing) {
            let newWidth = event.clientX - resizeOffsetX;
            let newHeight = event.clientY - resizeOffsetY;

            // Ensure the width and height are not less than the minimum size
            newWidth = Math.max(minWidth, newWidth);
            newHeight = Math.max(minHeight, newHeight);

            // Prevent resizing beyond maximum size
            newWidth = Math.min(newWidth, maxWidth - position.x);
            newHeight = Math.min(newHeight, maxHeight - position.y);

            setSize({ width: newWidth, height: newHeight });
        }
    };

    const stopDrag = () => {
        setDragging(false);
    };

    const stopResize = () => {
        setResizing(false);
    };

    const resetPosition = () => {
        setPosition(initialPosition);
        setSize(initialSize);
    };

    // Add mousemove and mouseup event listeners when dragging or resizing
    useEffect(() => {
        if (dragging || resizing) {
            document.addEventListener('mousemove', onMouseMove);
            document.addEventListener('mouseup', () => {
                stopDrag();
                stopResize();
            });
        }
        return () => {
            document.removeEventListener('mousemove', onMouseMove);
            document.removeEventListener('mouseup', () => {
                stopDrag();
                stopResize();
            });
        };
    }, [dragging, resizing]);

    return (
        <div
            className="screen"
            style={{
                left: `${position.x}px`,
                top: `${position.y}px`,
                width: `${size.width}px`,
                height: `${size.height}px`,
            }}
            ref={screenRef}
        >
            <div
                className="header"
                style={{ backgroundColor: headerColor }}
                onMouseDown={startDrag}
            >
                {headerText}
            </div>
            <div className="content">
                <p>{content}</p>
            </div>

            {/* Resize Handle */}
            <div
                className="resize-handle"
                onMouseDown={startResize}
                style={{ cursor: 'se-resize' }}
            ></div>

            {/* Reset Button */}
            <button onClick={resetPosition} className="reset-btn">
                Reset
            </button>
        </div>
    );
};

export default ScreenComponent;
