// src/App.tsx
import './app.css'
import ScreenComponent from "./components/ScreenComponent.tsx";

export function App() {
  return (
    <>
        <ScreenComponent
            headerText="My Custom Screen"
            initialPosition={{ x: 150, y: 150 }}
            initialSize={{ width: 400, height: 250 }}
            content="This is some content for the screen!"
            headerColor="#2196F3"
        />
        <ScreenComponent
            headerText="My Custom Screen"
            initialPosition={{ x: 750, y: 150 }}
            initialSize={{ width: 400, height: 250 }}
            content="This is some content for the screen!"
            headerColor="#2196F3"
        />
    </>
  )
}

// src/App.vue
<script setup>
import ScreenComponent from './components/ScreenComponent.vue';

</script>

<template>
  <main>
    <ScreenComponent
        headerText="Screen 1"
        :initialPosition="{ x: 100, y: 100 }"
        :initialSize="{ width: 300, height: 200 }"
        content="This is the content of Screen 1."
        headerColor="#FF5722"
    />
    <ScreenComponent
        headerText="Screen 2"
        :initialPosition="{ x: 500, y: 100 }"
        :initialSize="{ width: 300, height: 200 }"
        content="This is the content of Screen 2."
        headerColor="#3F51B5"
    />
  </main>
</template>

<style scoped>

</style>
